// Demo data for the application
export const demoUsers = [
  {
    id: '1',
    email: 'admin@demo.com',
    password: 'admin123',
    full_name: 'Admin Demo',
    role: 'super_admin',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '2',
    email: 'andy.hernandez@primelinedist.com',
    password: 'tech123',
    full_name: 'Andy Hernandez',
    role: 'technician',
    is_active: true,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: '3',
    email: 'sergio.tabares@primelinedist.com',
    password: 'tech123',
    full_name: 'Sergio Tabares',
    role: 'technician',
    is_active: true,
    created_at: '2026-01-16T00:00:00Z',
  },
  {
    id: '4',
    email: 'neftali.borrero@primelinedist.com',
    password: 'tech123',
    full_name: 'Neftali Borrero',
    role: 'technician',
    is_active: true,
    created_at: '2026-01-17T00:00:00Z',
  },
  {
    id: '5',
    email: 'Onier@primelinedist.com',
    password: 'tech123',
    full_name: 'Onier Guillen',
    role: 'technician',
    is_active: true,
    created_at: '2026-01-18T00:00:00Z',
  },
  {
    id: '6',
    email: 'Ernesto@primelinedist.com',
    password: 'tech123',
    full_name: 'Ernesto Sanchez',
    role: 'technician',
    is_active: true,
    created_at: '2026-01-19T00:00:00Z',
  },
  {
    id: '7',
    email: 'Alberto@primelinedist.com',
    password: 'tech123',
    full_name: 'Alberto Martinez',
    role: 'technician',
    is_active: true,
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: '8',
    email: 'oscar.encinas@primelinedist.com',
    password: 'tech123',
    full_name: 'Oscar Encinas',
    role: 'technician',
    is_active: true,
    created_at: '2026-01-21T00:00:00Z',
  },
  {
    id: '9',
    email: 'alejandro@eliaontheriver.com',
    password: 'tech123',
    full_name: 'Alejandro',
    role: 'technician',
    is_active: true,
    created_at: '2026-01-22T00:00:00Z',
  },
];

export const demoCompanies = [
  {
    id: '1',
    name: 'Café Central',
    address: 'Av. Principal 123',
    city: 'Ciudad de México',
    state: 'CDMX',
    postal_code: '01000',
    contact_name: 'María García',
    contact_email: 'maria@cafecentral.com',
    contact_phone: '555-1234',
    notes: 'Cliente preferencial - 3 máquinas',
    is_active: true,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '2',
    name: 'Hotel Plaza',
    address: 'Calle Reforma 456',
    city: 'Guadalajara',
    state: 'Jalisco',
    postal_code: '44100',
    contact_name: 'Carlos Ruiz',
    contact_email: 'carlos@hotelplaza.com',
    contact_phone: '333-5678',
    notes: '5 máquinas en diferentes pisos',
    is_active: true,
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: '3',
    name: 'Oficinas Tech Corp',
    address: 'Blvd. Tecnológico 789',
    city: 'Monterrey',
    state: 'Nuevo León',
    postal_code: '64000',
    contact_name: 'Ana López',
    contact_email: 'ana@techcorp.com',
    contact_phone: '818-9012',
    notes: 'Contrato anual de mantenimiento',
    is_active: true,
    created_at: '2026-02-01T00:00:00Z',
  },
];

export const demoTechnicians = [
  {
    id: '1',
    user_id: '2',
    employee_id: 'TECH-001',
    specialization: 'Espresso Machines',
    phone: '555-0101',
    certifications: 'Coffee equipment maintenance certified',
    notes: '5 years experience',
    is_active: true,
    created_at: '2026-01-15T00:00:00Z',
    user: demoUsers[1],
  },
  {
    id: '2',
    user_id: '3',
    employee_id: 'TECH-002',
    specialization: 'Espresso Machines',
    phone: '555-0102',
    certifications: 'Coffee equipment maintenance certified',
    notes: '3 years experience',
    is_active: true,
    created_at: '2026-01-16T00:00:00Z',
    user: demoUsers[2],
  },
  {
    id: '3',
    user_id: '4',
    employee_id: 'TECH-003',
    specialization: 'Grinders & Brewers',
    phone: '555-0103',
    certifications: 'Coffee equipment maintenance certified',
    notes: '4 years experience',
    is_active: true,
    created_at: '2026-01-17T00:00:00Z',
    user: demoUsers[3],
  },
  {
    id: '4',
    user_id: '5',
    employee_id: 'TECH-004',
    specialization: 'Espresso Machines',
    phone: '555-0104',
    certifications: 'Coffee equipment maintenance certified',
    notes: '6 years experience',
    is_active: true,
    created_at: '2026-01-18T00:00:00Z',
    user: demoUsers[4],
  },
  {
    id: '5',
    user_id: '6',
    employee_id: 'TECH-005',
    specialization: 'All equipment types',
    phone: '555-0105',
    certifications: 'Coffee equipment maintenance certified',
    notes: '7 years experience',
    is_active: true,
    created_at: '2026-01-19T00:00:00Z',
    user: demoUsers[5],
  },
  {
    id: '6',
    user_id: '7',
    employee_id: 'TECH-006',
    specialization: 'Espresso Machines',
    phone: '555-0106',
    certifications: 'Coffee equipment maintenance certified',
    notes: '3 years experience',
    is_active: true,
    created_at: '2026-01-20T00:00:00Z',
    user: demoUsers[6],
  },
  {
    id: '7',
    user_id: '8',
    employee_id: 'TECH-007',
    specialization: 'Grinders',
    phone: '555-0107',
    certifications: 'Coffee equipment maintenance certified',
    notes: '5 years experience',
    is_active: true,
    created_at: '2026-01-21T00:00:00Z',
    user: demoUsers[7],
  },
  {
    id: '8',
    user_id: '9',
    employee_id: 'TECH-008',
    specialization: 'All equipment types',
    phone: '555-0108',
    certifications: 'Coffee equipment maintenance certified',
    notes: '4 years experience',
    is_active: true,
    created_at: '2026-01-22T00:00:00Z',
    user: demoUsers[8],
  },
];

export const demoTechnicianCompanies = [
  // All technicians have access to all companies
  { technician_id: '1', company_id: '1', assigned_at: '2026-01-20T00:00:00Z' },
  { technician_id: '1', company_id: '2', assigned_at: '2026-01-22T00:00:00Z' },
  { technician_id: '1', company_id: '3', assigned_at: '2026-02-01T00:00:00Z' },
  { technician_id: '2', company_id: '1', assigned_at: '2026-01-20T00:00:00Z' },
  { technician_id: '2', company_id: '2', assigned_at: '2026-01-22T00:00:00Z' },
  { technician_id: '2', company_id: '3', assigned_at: '2026-02-01T00:00:00Z' },
  { technician_id: '3', company_id: '1', assigned_at: '2026-01-20T00:00:00Z' },
  { technician_id: '3', company_id: '2', assigned_at: '2026-01-22T00:00:00Z' },
  { technician_id: '3', company_id: '3', assigned_at: '2026-02-01T00:00:00Z' },
  { technician_id: '4', company_id: '1', assigned_at: '2026-01-20T00:00:00Z' },
  { technician_id: '4', company_id: '2', assigned_at: '2026-01-22T00:00:00Z' },
  { technician_id: '4', company_id: '3', assigned_at: '2026-02-01T00:00:00Z' },
  { technician_id: '5', company_id: '1', assigned_at: '2026-01-20T00:00:00Z' },
  { technician_id: '5', company_id: '2', assigned_at: '2026-01-22T00:00:00Z' },
  { technician_id: '5', company_id: '3', assigned_at: '2026-02-01T00:00:00Z' },
  { technician_id: '6', company_id: '1', assigned_at: '2026-01-20T00:00:00Z' },
  { technician_id: '6', company_id: '2', assigned_at: '2026-01-22T00:00:00Z' },
  { technician_id: '6', company_id: '3', assigned_at: '2026-02-01T00:00:00Z' },
  { technician_id: '7', company_id: '1', assigned_at: '2026-01-20T00:00:00Z' },
  { technician_id: '7', company_id: '2', assigned_at: '2026-01-22T00:00:00Z' },
  { technician_id: '7', company_id: '3', assigned_at: '2026-02-01T00:00:00Z' },
  { technician_id: '8', company_id: '1', assigned_at: '2026-01-20T00:00:00Z' },
  { technician_id: '8', company_id: '2', assigned_at: '2026-01-22T00:00:00Z' },
  { technician_id: '8', company_id: '3', assigned_at: '2026-02-01T00:00:00Z' },
];

export const demoForms = [
  {
    id: '1',
    name: 'Mantenimiento Preventivo',
    description: 'Revisión completa de máquinas de café',
    category: 'Mantenimiento',
    is_active: true,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '2',
    name: 'Reparación Correctiva',
    description: 'Diagnóstico y reparación de fallas',
    category: 'Reparación',
    is_active: true,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '3',
    name: 'Instalación de Equipo',
    description: 'Instalación y configuración inicial',
    category: 'Instalación',
    is_active: true,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '4',
    name: 'CF103 - Service Order',
    description: 'Orden de servicio completa con equipos, partes y mano de obra',
    category: 'Service Order',
    is_active: true,
    created_at: '2026-01-10T00:00:00Z',
  },
];

export const demoFormFields = [
  // Campos para Mantenimiento Preventivo
  {
    id: '1',
    form_id: '1',
    field_name: 'modelo_maquina',
    field_label: 'Modelo de Máquina',
    field_type: 'text' as const,
    placeholder: 'Ej: Gaggia Classic Pro',
    is_required: true,
    order_index: 1,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '2',
    form_id: '1',
    field_name: 'numero_serie',
    field_label: 'Número de Serie',
    field_type: 'text' as const,
    placeholder: 'Número de serie del equipo',
    is_required: true,
    order_index: 2,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '3',
    form_id: '1',
    field_name: 'estado_general',
    field_label: 'Estado General',
    field_type: 'select' as const,
    options: ['Excelente', 'Bueno', 'Regular', 'Malo'],
    is_required: true,
    order_index: 3,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '4',
    form_id: '1',
    field_name: 'limpieza_realizada',
    field_label: 'Limpieza Realizada',
    field_type: 'checkbox' as const,
    options: [
      'Grupo de café',
      'Portafiltros',
      'Vaporera',
      'Bandeja recolectora',
      'Exterior',
    ],
    is_required: true,
    order_index: 4,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '5',
    form_id: '1',
    field_name: 'observaciones',
    field_label: 'Observaciones',
    field_type: 'textarea' as const,
    placeholder: 'Detalles adicionales del servicio...',
    is_required: false,
    order_index: 5,
    created_at: '2026-01-05T00:00:00Z',
  },
  // Campos para Reparación Correctiva
  {
    id: '6',
    form_id: '2',
    field_name: 'descripcion_falla',
    field_label: 'Descripción de la Falla',
    field_type: 'textarea' as const,
    placeholder: 'Describe el problema reportado...',
    is_required: true,
    order_index: 1,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '7',
    form_id: '2',
    field_name: 'diagnostico',
    field_label: 'Diagnóstico',
    field_type: 'textarea' as const,
    placeholder: 'Causa del problema...',
    is_required: true,
    order_index: 2,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '8',
    form_id: '2',
    field_name: 'reparacion_realizada',
    field_label: 'Reparación Realizada',
    field_type: 'textarea' as const,
    placeholder: 'Describe la reparación...',
    is_required: true,
    order_index: 3,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: '9',
    form_id: '2',
    field_name: 'piezas_reemplazadas',
    field_label: 'Piezas Reemplazadas',
    field_type: 'text' as const,
    placeholder: 'Lista de piezas',
    is_required: false,
    order_index: 4,
    created_at: '2026-01-05T00:00:00Z',
  },
  // Campos para CF103 - Service Order
  {
    id: '10',
    form_id: '4',
    field_name: 'date',
    field_label: 'Date',
    field_type: 'date' as const,
    is_required: true,
    order_index: 1,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '11',
    form_id: '4',
    field_name: 'technician',
    field_label: 'Technician',
    field_type: 'text' as const,
    placeholder: 'Technician name',
    is_required: true,
    order_index: 2,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '12',
    form_id: '4',
    field_name: 'customer_name',
    field_label: 'Customer Name',
    field_type: 'text' as const,
    placeholder: 'Customer name',
    is_required: true,
    order_index: 3,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '13',
    form_id: '4',
    field_name: 'customer_email',
    field_label: 'Customer Email',
    field_type: 'email' as const,
    placeholder: 'customer@email.com',
    is_required: false,
    order_index: 4,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '14',
    form_id: '4',
    field_name: 'tech_email',
    field_label: 'Tech Email',
    field_type: 'email' as const,
    placeholder: 'tech@email.com',
    is_required: true,
    order_index: 5,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '15',
    form_id: '4',
    field_name: 'sales_manager_email',
    field_label: 'Sales Manager Email',
    field_type: 'email' as const,
    placeholder: 'manager@email.com',
    is_required: true,
    order_index: 6,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '16',
    form_id: '4',
    field_name: 'property',
    field_label: 'Property',
    field_type: 'radio' as const,
    options: ['PLD', 'La Colombe', 'Owner'],
    is_required: true,
    order_index: 7,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '17',
    form_id: '4',
    field_name: 'service_type',
    field_label: 'Service Type',
    field_type: 'checkbox' as const,
    options: ['Delivery', 'Pick up', 'Service', 'Tune up', 'Training', 'Other'],
    is_required: true,
    order_index: 8,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '18',
    form_id: '4',
    field_name: 'espresso_brand_model',
    field_label: 'Espresso Brand & Model',
    field_type: 'text' as const,
    placeholder: 'Espresso machine brand and model',
    is_required: false,
    order_index: 9,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '19',
    form_id: '4',
    field_name: 'espresso_serial',
    field_label: 'Espresso Serial Number',
    field_type: 'text' as const,
    placeholder: 'Serial number',
    is_required: false,
    order_index: 10,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '20',
    form_id: '4',
    field_name: 'grinder_brand_model',
    field_label: 'Coffee Grinder Brand & Model',
    field_type: 'text' as const,
    placeholder: 'Grinder brand and model',
    is_required: false,
    order_index: 11,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '21',
    form_id: '4',
    field_name: 'grinder_serial',
    field_label: 'Coffee Grinder Serial Number',
    field_type: 'text' as const,
    placeholder: 'Serial number',
    is_required: false,
    order_index: 12,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '22',
    form_id: '4',
    field_name: 'drip_brand_model',
    field_label: 'Drip Brewer Brand & Model',
    field_type: 'text' as const,
    placeholder: 'Drip brewer brand and model',
    is_required: false,
    order_index: 13,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '23',
    form_id: '4',
    field_name: 'drip_serial',
    field_label: 'Drip Brewer Serial Number',
    field_type: 'text' as const,
    placeholder: 'Serial number',
    is_required: false,
    order_index: 14,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '24',
    form_id: '4',
    field_name: 'parts_details',
    field_label: 'Parts',
    field_type: 'textarea' as const,
    placeholder: 'List parts used: Qty, Part Number, Description, Unit Price',
    help_text: 'Enter parts information (one per line)',
    is_required: false,
    order_index: 15,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '25',
    form_id: '4',
    field_name: 'workforce_hours',
    field_label: 'Workforce Hours',
    field_type: 'number' as const,
    placeholder: 'Total hours',
    is_required: false,
    order_index: 16,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '26',
    form_id: '4',
    field_name: 'workforce_notes',
    field_label: 'Workforce Notes',
    field_type: 'textarea' as const,
    placeholder: 'Work performed details',
    is_required: false,
    order_index: 17,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '27',
    form_id: '4',
    field_name: 'price_per_hour',
    field_label: 'Price/Hr',
    field_type: 'number' as const,
    placeholder: '0.00',
    is_required: false,
    order_index: 18,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '28',
    form_id: '4',
    field_name: 'grand_total',
    field_label: 'Grand Total',
    field_type: 'number' as const,
    placeholder: '0.00',
    is_required: false,
    order_index: 19,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '29',
    form_id: '4',
    field_name: 'photos',
    field_label: 'Photos',
    field_type: 'file' as const,
    help_text: 'Take pictures of the equipment and serial number of all the equipment serviced',
    is_required: true,
    order_index: 20,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '30',
    form_id: '4',
    field_name: 'job_description',
    field_label: 'Nature of labor performed (Job Description)',
    field_type: 'textarea' as const,
    placeholder: 'Describe the work performed...',
    is_required: true,
    order_index: 21,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '31',
    form_id: '4',
    field_name: 'customer_signature',
    field_label: 'Customer Signature',
    field_type: 'signature' as const,
    is_required: true,
    order_index: 22,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: '32',
    form_id: '4',
    field_name: 'print_name',
    field_label: 'Print Name',
    field_type: 'text' as const,
    placeholder: 'Customer printed name',
    is_required: true,
    order_index: 23,
    created_at: '2026-01-10T00:00:00Z',
  },
];

export const demoReports = [
  {
    id: '1',
    company_id: '1',
    technician_id: '1',
    form_id: '1',
    form_data: {
      modelo_maquina: 'Gaggia Classic Pro',
      numero_serie: 'GCP-2023-456',
      estado_general: 'Bueno',
      limpieza_realizada: ['Grupo de café', 'Portafiltros', 'Exterior'],
      observaciones: 'Servicio completado sin problemas. Recomendado cambio de empaque en 3 meses.',
    },
    status: 'completed',
    notes: 'Cliente satisfecho con el servicio',
    submitted_at: '2026-02-10T10:30:00Z',
    reviewed_at: '2026-02-10T14:00:00Z',
    created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: '2',
    company_id: '2',
    technician_id: '1',
    form_id: '2',
    form_data: {
      descripcion_falla: 'La máquina no calienta el agua',
      diagnostico: 'Resistencia quemada',
      reparacion_realizada: 'Reemplazo de resistencia y termostato',
      piezas_reemplazadas: 'Resistencia 1400W, Termostato',
    },
    status: 'completed',
    notes: 'Se realizó prueba exitosa. Garantía de 30 días en piezas.',
    submitted_at: '2026-02-12T15:00:00Z',
    reviewed_at: '2026-02-12T16:30:00Z',
    created_at: '2026-02-12T14:30:00Z',
  },
  {
    id: '3',
    company_id: '3',
    technician_id: '1',
    form_id: '1',
    form_data: {
      modelo_maquina: 'Rancilio Silvia',
      numero_serie: 'RS-2024-789',
      estado_general: 'Excelente',
      limpieza_realizada: ['Grupo de café', 'Portafiltros', 'Vaporera', 'Bandeja recolectora', 'Exterior'],
      observaciones: 'Equipo en excelentes condiciones. Mantenimiento regular.',
    },
    status: 'submitted',
    notes: null,
    submitted_at: '2026-02-14T09:15:00Z',
    reviewed_at: null,
    created_at: '2026-02-14T09:00:00Z',
  },
];

export const demoReportPhotos = [
  {
    id: '1',
    report_id: '1',
    file_name: 'maquina_antes.jpg',
    file_url: 'demo/maquina_antes.jpg',
    file_size: 524288,
    uploaded_at: '2026-02-10T10:15:00Z',
  },
  {
    id: '2',
    report_id: '1',
    file_name: 'maquina_despues.jpg',
    file_url: 'demo/maquina_despues.jpg',
    file_size: 487424,
    uploaded_at: '2026-02-10T10:20:00Z',
  },
];

// Función helper para obtener empresas asignadas a un técnico
export const getCompaniesForTechnician = (technicianId: string) => {
  const assignedCompanyIds = demoTechnicianCompanies
    .filter((tc) => tc.technician_id === technicianId)
    .map((tc) => tc.company_id);

  return demoCompanies.filter((c) => assignedCompanyIds.includes(c.id));
};

// Función helper para obtener reportes con datos relacionados
export const getReportSummaries = () => {
  return demoReports.map((report) => {
    const company = demoCompanies.find((c) => c.id === report.company_id);
    const technician = demoTechnicians.find((t) => t.id === report.technician_id);
    const form = demoForms.find((f) => f.id === report.form_id);
    const photos = demoReportPhotos.filter((p) => p.report_id === report.id);

    return {
      ...report,
      company_name: company?.name || 'N/A',
      technician_name: technician?.user.full_name || 'N/A',
      form_name: form?.name || 'N/A',
      photo_count: photos.length,
    };
  });
};
